# All values in no of frames
BACKGROUND_COLOR: [77, 77, 77]
STIM_COLOR: [239, 228, 176]
STIM_LETTER_COLOR: [0, 0 ,0]
STIM_LAST_COLOR: [255, 201, 14]
FRAME_COLOR: [195, 195, 195]
FRAME_BACKGROUND: [127, 127, 127]
TEXT_COLOR: [255, 255, 255]
LINE_COLOR: [239, 228, 176]
MAX_TEST_TIME: 30
MAX_A_TIME: 50
MAX_B_TIME: 150
FRAME_RATE: 60
QUE_RADIUS: 27
LINE_WIDTH: 5
STIM_LETTERS: ←→↑↓



